import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Topbar from "./components/Topbar";
import Navbar from "./components/Navbar";

// Importing fonts
const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-roboto-mono", // Updated font variable
});

const geistMono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono", // Updated font variable for clarity
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Import Header and Footer Components
 // Update with correct path
 // Update with correct path

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoMono.variable} ${geistMono.variable} antialiased`}
      >
        {/* Header Component */}
        <Topbar/>
        <Header/>
        <Navbar/>
        
        {/* Main Content */}
        <main>{children}</main>
        
        {/* Footer Component */}
        <Footer/>
      </body>
    </html>
  );
}
